# Generated by Django 4.2.3 on 2023-07-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_my_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_future_trips',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nacionality',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
