# Generated by Django 4.2.3 on 2023-08-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_message_location_alter_trip_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Publication',
        ),
    ]
