# Generated by Django 4.2.3 on 2024-01-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_message_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='likes',
        ),
    ]
