# Generated by Django 4.2.3 on 2024-01-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_publication_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.TextField(default=21),
            preserve_default=False,
        ),
    ]
