# Generated by Django 4.2.3 on 2023-07-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_trip_delete_image_remove_userprofile_my_future_trips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
