# Generated by Django 4.2.3 on 2023-07-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_trip_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='No has seleccionado ninguna descripcion', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_profile',
            field=models.TextField(default='https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg'),
        ),
    ]
