# Generated by Django 4.2.3 on 2024-01-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_publication_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='likes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
