# Generated by Django 4.2.3 on 2023-07-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_profile',
            field=models.TextField(blank=True),
        ),
    ]
