# Generated by Django 4.2.3 on 2023-07-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_userprofile_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_portate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nacionality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
