# Generated by Django 4.2.3 on 2023-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_image_portate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_portate',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
