# Generated by Django 4.2.3 on 2023-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_userprofile_image_portate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_portate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_profile',
            field=models.TextField(blank=True),
        ),
    ]
