# Generated by Django 4.2.3 on 2023-07-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
