# Generated by Django 4.2.3 on 2023-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_message_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
