# Generated by Django 4.2.3 on 2023-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.JSONField(blank=True, default={'followings': []}, null=True),
        ),
    ]
