# Generated by Django 4.2.3 on 2023-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_create_by_livingroom_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.AddField(
            model_name='livingroom',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='chat.message'),
        ),
    ]
